### ISSUE TITLE
When training full dataset raise RuntimeError: CUDA error

### ISSUE THREAD

**Issue by HannahHan1119** [microsoft/SoftTeacher#120]
Hi!

When I run `bash tools/dist_train.sh configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_full_720k.py 2`, raise CUDA error: CUBLAS_STATUS_EXECUTION_FAILED 
![image](https://user-images.githubusercontent.com/92434145/143420013-7f7bb98e-6ed1-447e-816d-f4d0079b2bc3.png)
Is it about preparing wrong instances_unlabeled2017.json? If any suggest, let me know!

Thanks!

**Comment by HannahHan1119** [comment]
I tried with a gpu, it still raise the error.

**Comment by MendelXu** [comment]
I am not sure what the error indicates. Could you try to train a supervised model with mmdetection?

**Comment by HannahHan1119** [comment]
I have no problem in training faster rcnn with mmdetection. 
I guess that the reason maybe somewhere the shape could not natch. So I print(bbox_feats.shape) in https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/roi_heads/standard_roi_head.py#L124. And I got here https://github.com/microsoft/SoftTeacher/blob/main/ssod/models/soft_teacher.py#L422 raise the CUDA error.
![image](https://user-images.githubusercontent.com/92434145/144156524-ff7202ba-9b1c-481e-b6a0-3ef20dbda40d.png)
I guess that proposal is fewer and it causes the error in faster rcnn. Is it reasonable?

**Comment by MendelXu** [comment]
I think it is not the reason. Could you try to change it to `fp32` model? (comment `fp16=dict(...)` in the config file).

**Comment by HannahHan1119** [comment]
Yes, it still raise the same error. 
I find that my pytorch version is 1.8. So, I will switch pytorch version to 1.9 and keep trying.

**Comment by HannahHan1119** [comment]
I use pytorch1.9 and the problem solved.
Thanks.
