### ISSUE TITLE
Error while trying to train with 4 gpus

### ISSUE THREAD

**Issue by sobujmaroon** [microsoft/SoftTeacher#39]
Congratulations for the great work. I am getting this error while trying to train with 4 gpus. Can you please help me out?
```
File "/data/SoftTeacher/tools/train.py", line 198, in <module>
    main()
  File "/data/SoftTeacher/tools/train.py", line 186, in main
    train_detector(
  File "/data/SoftTeacher/ssod/apis/train.py", line 206, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/SoftTeacher/ssod/models/soft_teacher.py", line 44, in forward_train
    sup_loss = self.student.forward_train(**data_groups["sup"])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 59, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 152, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 244, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/data/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:360: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 198, in <module>
    main()
  File "/data/SoftTeacher/tools/train.py", line 186, in main
    train_detector(
  File "/data/SoftTeacher/ssod/apis/train.py", line 206, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/SoftTeacher/ssod/models/soft_teacher.py", line 44, in forward_train
    sup_loss = self.student.forward_train(**data_groups["sup"])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 59, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 152, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 244, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/data/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:360: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 198, in <module>
    main()
  File "/data/SoftTeacher/tools/train.py", line 186, in main
    train_detector(
  File "/data/SoftTeacher/ssod/apis/train.py", line 206, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/SoftTeacher/ssod/models/soft_teacher.py", line 44, in forward_train
    sup_loss = self.student.forward_train(**data_groups["sup"])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 59, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 152, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 244, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
/data/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:324: UserWarning: ``grid_anchors`` would be deprecated soon. Please use ``grid_priors`` 
  warnings.warn('``grid_anchors`` would be deprecated soon. '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/core/anchor/anchor_generator.py:360: UserWarning: ``single_level_grid_anchors`` would be deprecated soon. Please use ``single_level_grid_priors`` 
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 198, in <module>
    main()
  File "/data/SoftTeacher/tools/train.py", line 186, in main
    train_detector(
  File "/data/SoftTeacher/ssod/apis/train.py", line 206, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 133, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/parallel/distributed.py", line 52, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 238, in train_step
    losses = self(**data)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 128, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/base.py", line 172, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/data/SoftTeacher/ssod/models/soft_teacher.py", line 44, in forward_train
    sup_loss = self.student.forward_train(**data_groups["sup"])
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/detectors/two_stage.py", line 135, in forward_train
    rpn_losses, proposal_list = self.rpn_head.forward_train(
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/base_dense_head.py", line 59, in forward_train
    proposal_list = self.get_bboxes(*outs, img_metas, cfg=proposal_cfg)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/runner/fp16_utils.py", line 214, in new_func
    output = old_func(*new_args, **new_kwargs)
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 152, in get_bboxes
    proposals = self._get_bboxes_single(cls_score_list, bbox_pred_list,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/dense_heads/rpn_head.py", line 244, in _get_bboxes_single
    dets, keep = batched_nms(proposals, scores, ids, cfg.nms)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 307, in batched_nms
    dets, keep = nms_op(boxes_for_nms, scores, **nms_cfg_)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/misc.py", line 330, in new_func
    output = old_func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 171, in nms
    inds = NMSop.apply(boxes, scores, iou_threshold, offset,
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/nms.py", line 26, in forward
    inds = ext_module.nms(
RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

wandb: Waiting for W&B process to finish, PID 38162
wandb: Program failed with code 1. 
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 1 (pid: 37922) of binary: /home/ubuntu/anaconda3/envs/py39/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 689, in run
    elastic_launch(
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 244, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
**************************************************
              tools/train.py FAILED               
==================================================
Root Cause:
[0]:
  time: 2021-09-29_15:26:15
  rank: 1 (local_rank: 1)
  exitcode: -11 (pid: 37922)
  error_file: <N/A>
  msg: "Signal 11 (SIGSEGV) received by PID 37922"
==================================================
Other Failures:
[1]:
  time: 2021-09-29_15:26:15
  rank: 3 (local_rank: 3)
  exitcode: -11 (pid: 37924)
  error_file: <N/A>
  msg: "Signal 11 (SIGSEGV) received by PID 37924"
**************************************************
```

**Comment by MendelXu** [comment]
Could you tell me what command you are running?

**Comment by sobujmaroon** [comment]
```bash tools/dist_train_partially.sh semi 1 1 4```
I think the error is caused by ```mmdetection```. How do I install older(specified in your repository) version of ```mmdetection```?

**Comment by MendelXu** [comment]
You can go to the directory `thirdparty/mmdetection` and run `git checkout v2.16.0`. 
By the way, I have tried to install the newest version of mmdetection and it works well. Could you post the full log here?

**Comment by sobujmaroon** [comment]
```
+ TYPE=semi
+ FOLD=1
+ PERCENT=1
+ GPUS=4
+ PORT=29500
++ dirname tools/dist_train_partially.sh
+ PYTHONPATH=tools/..:
+ [[ semi == \b\a\s\e\l\i\n\e ]]
++ dirname tools/dist_train_partially.sh
+ python -m torch.distributed.launch --nproc_per_node=4 --master_port=29500 tools/train.py configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_180k.py --launcher pytorch --cfg-options fold=1 percent=1
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py:26: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 15, in <module>
    from mmdet.models import build_detector
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py)
/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py:26: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 15, in <module>
    from mmdet.models import build_detector
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py)
/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py:26: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 15, in <module>
    from mmdet.models import build_detector
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py)
/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py:28: UserWarning: Fail to import ``MultiScaleDeformableAttention`` from ``mmcv.ops.multi_scale_deform_attn``, You should install ``mmcv-full`` if you need this module. 
  warnings.warn('Fail to import ``MultiScaleDeformableAttention`` from '
/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py:26: UserWarning: `MultiScaleDeformableAttention` in MMCV has been moved to `mmcv.ops.multi_scale_deform_attn`, please update your MMCV
  warnings.warn(
Traceback (most recent call last):
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 23, in <module>
    from mmcv.ops.multi_scale_deform_attn import MultiScaleDeformableAttention
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .ball_query import ball_query
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/ops/ball_query.py", line 7, in <module>
    ext_module = ext_loader.load_ext('_ext', ['ball_query_forward'])
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/SoftTeacher/tools/train.py", line 15, in <module>
    from mmdet.models import build_detector
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/__init__.py", line 2, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/__init__.py", line 2, in <module>
    from .csp_darknet import CSPDarknet
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/backbones/csp_darknet.py", line 11, in <module>
    from ..utils import CSPLayer
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/__init__.py", line 16, in <module>
    from .transformer import (DetrTransformerDecoder, DetrTransformerDecoderLayer,
  File "/data/SoftTeacher/thirdparty/mmdetection/mmdet/models/utils/transformer.py", line 29, in <module>
    from mmcv.cnn.bricks.transformer import MultiScaleDeformableAttention
ImportError: cannot import name 'MultiScaleDeformableAttention' from 'mmcv.cnn.bricks.transformer' (/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/mmcv/cnn/bricks/transformer.py)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/ubuntu/anaconda3/envs/py39/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/soft_teacher/soft_teacher_faster_rcnn_r50_caffe_fpn_coco_180k.py', '--launcher', 'pytorch', '--cfg-options', 'fold=1', 'percent=1']' returned non-zero exit status 1.
```

**Comment by MendelXu** [comment]
`mmcv/_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZN2at5sliceERKNS_6TensorElN3c108optionalIlEES5_l` 
The error indicates that your `mmcv` is not compatible with your pytorch. Maybe you can uninstall and  reinstall the `mmcv`.

**Comment by sobujmaroon** [comment]
Reinstalled ```mmcv``` but the issue still persists. This error always pops up: ```RuntimeError: CUDA error: invalid device function
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.```. And I am also getting these:
```[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 2 using best-guess GPU 2 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 3 using best-guess GPU 3 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.```

**Comment by MendelXu** [comment]
It is very wierd~could you post your environment here? 
1) What is your system version and Cuda version?
2) What is your pip environment? ( Paste the result of `pip list` or `conda list` here.)

**Comment by sobujmaroon** [comment]
For Q1:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.91.03    Driver Version: 460.91.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1B.0 Off |                    0 |
| N/A   23C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:00:1C.0 Off |                    0 |
| N/A   23C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            On   | 00000000:00:1D.0 Off |                    0 |
| N/A   24C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   22C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
For Q2:
```
# packages in environment at /home/ubuntu/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2018.12                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.6                    py37_0  
anaconda-project          0.8.2                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.1.0                    py37_0  
astropy                   3.1              py37h7b6447c_0  
atomicwrites              1.2.1                    py37_0  
attrs                     18.2.0           py37h28b3542_0  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.6.3                    py37_0  
bitarray                  0.8.3            py37h14c3975_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py37_0  
bleach                    3.0.2                    py37_0  
blosc                     1.14.4               hdbcaa40_0  
bokeh                     1.0.2                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h035aef0_1  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37he75722e_1  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
cloudpickle               0.6.1                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
conda                     4.5.12                   py37_0  
conda-build               3.17.6                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.4.2            py37h1ba5d50_0  
curl                      7.63.0            hbc83047_1000  
cycler                    0.10.0                   py37_0  
cython                    0.29.2           py37he6710b0_0  
cytoolz                   0.9.0.1          py37h14c3975_1  
dask                      1.0.0                    py37_0  
dask-core                 1.0.0                    py37_0  
datashape                 0.5.4                    py37_1  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py37_0  
defusedxml                0.5.0                    py37_1  
distributed               1.25.1                   py37_0  
docutils                  0.14                     py37_0  
entrypoints               0.2.3                    py37_2  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py37h14c3975_2  
filelock                  3.0.10                   py37_0  
flask                     1.0.2                    py37_1  
flask-cors                3.0.7                    py37_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
fribidi                   1.0.5                h7b6447c_0  
future                    0.17.1                   py37_0  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.3.7            py37h7b6447c_1  
glib                      2.56.2               hd408876_0  
glob2                     0.6                      py37_1  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py37h10f8cd9_2  
graphite2                 1.3.12               h23475e2_2  
greenlet                  0.4.15           py37h7b6447c_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py37h989c5e5_3  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
imageio                   2.4.1                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.6                      py37_0  
intel-openmp              2019.1                      144  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.2.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.4                    py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py37_0  
jedi                      0.13.2                   py37_0  
jeepney                   0.4                      py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.3                   py37_0  
jupyterlab_server         0.2.0                    py37_0  
keyring                   17.0.0                   py37_0  
kiwisolver                1.0.1            py37hf484d3e_0  
krb5                      1.16.1               h173b8e3_7  
lazy-object-proxy         1.3.1            py37h14c3975_2  
libarchive                3.3.3                h5d8350f_5  
libcurl                   7.63.0            h20c2e04_1000  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblief                   0.9.0                h7725739_1  
libpng                    1.6.35               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h1ba5d50_4  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he85c1e1_2  
libtool                   2.4.6                h7b6447c_5  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
llvmlite                  0.26.0           py37hd408876_0  
locket                    0.2.0                    py37_1  
lxml                      4.2.5            py37hefd8a0e_0  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.1.0            py37h7b6447c_0  
matplotlib                3.0.2            py37h5429711_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.1                      144  
mkl-service               1.1.2            py37he904b0f_5  
mkl_fft                   1.0.6            py37hd81dba3_0  
mkl_random                1.0.2            py37hd81dba3_0  
more-itertools            4.3.0                    py37_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.5.6            py37h6bb024c_1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.4.0                    py37_1  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                      py37_1  
nltk                      3.4                      py37_1  
nose                      1.3.7                    py37_2  
notebook                  5.7.4                    py37_0  
numba                     0.41.0           py37h962f231_0  
numexpr                   2.6.8            py37h9e4a6bb_0  
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
numpydoc                  0.8.0                    py37_0  
odo                       0.5.1                    py37_0  
olefile                   0.46                     py37_0  
openpyxl                  2.5.12                   py37_0  
openssl                   1.1.1a               h7b6447c_0  
packaging                 18.0                     py37_0  
pandas                    0.23.4           py37h04863e7_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2                    py37_1  
pango                     1.42.4               h049681c_0  
parso                     0.3.1                    py37_0  
partd                     0.3.9                    py37_0  
patchelf                  0.9                  he6710b0_3  
path.py                   11.5.0                   py37_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.3.0            py37h34e0f95_0  
pip                       18.1                     py37_0  
pixman                    0.34.0               hceecf20_3  
pkginfo                   1.4.2                    py37_1  
pluggy                    0.8.0                    py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.5.0                    py37_0  
prompt_toolkit            2.0.7                    py37_0  
psutil                    5.4.8            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py                        1.7.0                    py37_0  
py-lief                   0.9.0            py37h7725739_1  
pycodestyle               2.4.0                    py37_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h14c3975_9  
pycurl                    7.43.0.2         py37h1ba5d50_0  
pyflakes                  2.0.0                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.2.2                    py37_0  
pyodbc                    4.0.25           py37he6710b0_0  
pyopenssl                 18.0.0                   py37_0  
pyparsing                 2.3.0                    py37_0  
pyqt                      5.9.2            py37h05f1152_2  
pysocks                   1.6.8                    py37_0  
pytables                  3.4.4            py37ha205bf6_0  
pytest                    4.0.2                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.2.0                    py37_0  
pytest-openfiles          0.3.1                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.1                h0371630_7  
python-dateutil           2.7.5                    py37_0  
python-libarchive-c       2.8                      py37_6  
pytz                      2018.7                   py37_0  
pywavelets                1.0.1            py37hdd07704_0  
pyyaml                    3.13             py37h14c3975_0  
pyzmq                     17.1.2           py37h14c3975_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.5.3                    py37_0  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.5.2                    py37_0  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
rope                      0.11.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
scikit-image              0.14.1           py37he6710b0_0  
scikit-learn              0.20.1           py37hd81dba3_0  
scipy                     1.1.0            py37h7c811a0_2  
seaborn                   0.9.0                    py37_0  
secretstorage             3.1.0                    py37_0  
send2trash                1.5.0                    py37_0  
setuptools                40.6.3                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.0.1                    py37_0  
sortedcontainers          2.1.0                    py37_0  
sphinx                    1.8.2                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.2                    py37_0  
spyder-kernels            0.3.0                    py37_0  
sqlalchemy                1.2.15           py37h7b6447c_0  
sqlite                    3.26.0               h7b6447c_0  
statsmodels               0.9.0            py37h035aef0_0  
sympy                     1.3                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py37_0  
tornado                   5.1.1            py37h7b6447c_0  
tqdm                      4.28.1           py37h28b3542_0  
traitlets                 4.3.2                    py37_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h14c3975_0  
urllib3                   1.24.1                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.32.3                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
wrapt                     1.10.11          py37h14c3975_2  
wurlitzer                 1.0.2                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.2                    py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hf484d3e_1  
zict                      0.1.3                    py37_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

**Comment by MendelXu** [comment]
Could you post the pip environment? It seems there are no packages like pytorch and mmdet in the conda environment.

**Comment by sobujmaroon** [comment]
```
Package                            Version   
---------------------------------- ----------
alabaster                          0.7.12    
anaconda-client                    1.7.2     
anaconda-navigator                 1.9.6     
anaconda-project                   0.8.2     
asn1crypto                         0.24.0    
astroid                            2.1.0     
astropy                            3.1       
atomicwrites                       1.2.1     
attrs                              18.2.0    
Babel                              2.6.0     
backcall                           0.1.0     
backports.os                       0.1.1     
backports.shutil-get-terminal-size 1.0.0     
beautifulsoup4                     4.6.3     
bitarray                           0.8.3     
bkcharts                           0.2       
blaze                              0.11.3    
bleach                             3.0.2     
bokeh                              1.0.2     
boto                               2.49.0    
Bottleneck                         1.2.1     
certifi                            2018.11.29
cffi                               1.11.5    
chardet                            3.0.4     
Click                              7.0       
cloudpickle                        0.6.1     
clyent                             1.2.2     
colorama                           0.4.1     
conda                              4.5.12    
conda-build                        3.17.6    
conda-verify                       3.1.1     
contextlib2                        0.5.5     
cryptography                       2.4.2     
cycler                             0.10.0    
Cython                             0.29.2    
cytoolz                            0.9.0.1   
dask                               1.0.0     
datashape                          0.5.4     
decorator                          4.3.0     
defusedxml                         0.5.0     
distributed                        1.25.1    
docutils                           0.14      
entrypoints                        0.2.3     
et-xmlfile                         1.0.1     
fastcache                          1.0.2     
filelock                           3.0.10    
Flask                              1.0.2     
Flask-Cors                         3.0.7     
future                             0.17.1    
gevent                             1.3.7     
glob2                              0.6       
gmpy2                              2.0.8     
greenlet                           0.4.15    
h5py                               2.8.0     
heapdict                           1.0.0     
html5lib                           1.0.1     
idna                               2.8       
imageio                            2.4.1     
imagesize                          1.1.0     
importlib-metadata                 0.6       
ipykernel                          5.1.0     
ipython                            7.2.0     
ipython-genutils                   0.2.0     
ipywidgets                         7.4.2     
isort                              4.3.4     
itsdangerous                       1.1.0     
jdcal                              1.4       
jedi                               0.13.2    
jeepney                            0.4       
Jinja2                             2.10      
jsonschema                         2.6.0     
jupyter                            1.0.0     
jupyter-client                     5.2.4     
jupyter-console                    6.0.0     
jupyter-core                       4.4.0     
jupyterlab                         0.35.3    
jupyterlab-server                  0.2.0     
keyring                            17.0.0    
kiwisolver                         1.0.1     
lazy-object-proxy                  1.3.1     
libarchive-c                       2.8       
lief                               0.9.0     
llvmlite                           0.26.0    
locket                             0.2.0     
lxml                               4.2.5     
MarkupSafe                         1.1.0     
matplotlib                         3.0.2     
mccabe                             0.6.1     
mistune                            0.8.4     
mkl-fft                            1.0.6     
mkl-random                         1.0.2     
more-itertools                     4.3.0     
mpmath                             1.1.0     
msgpack                            0.5.6     
multipledispatch                   0.6.0     
navigator-updater                  0.2.1     
nbconvert                          5.4.0     
nbformat                           4.4.0     
networkx                           2.2       
nltk                               3.4       
nose                               1.3.7     
notebook                           5.7.4     
numba                              0.41.0    
numexpr                            2.6.8     
numpy                              1.15.4    
numpydoc                           0.8.0     
odo                                0.5.1     
olefile                            0.46      
openpyxl                           2.5.12    
packaging                          18.0      
pandas                             0.23.4    
pandocfilters                      1.4.2     
parso                              0.3.1     
partd                              0.3.9     
path.py                            11.5.0    
pathlib2                           2.3.3     
patsy                              0.5.1     
pep8                               1.7.1     
pexpect                            4.6.0     
pickleshare                        0.7.5     
Pillow                             5.3.0     
pip                                18.1      
pkginfo                            1.4.2     
pluggy                             0.8.0     
ply                                3.11      
prometheus-client                  0.5.0     
prompt-toolkit                     2.0.7     
psutil                             5.4.8     
ptyprocess                         0.6.0     
py                                 1.7.0     
pycodestyle                        2.4.0     
pycosat                            0.6.3     
pycparser                          2.19      
pycrypto                           2.6.1     
pycurl                             7.43.0.2  
pyflakes                           2.0.0     
Pygments                           2.3.1     
pylint                             2.2.2     
pyodbc                             4.0.25    
pyOpenSSL                          18.0.0    
pyparsing                          2.3.0     
PySocks                            1.6.8     
pytest                             4.0.2     
pytest-arraydiff                   0.3       
pytest-astropy                     0.5.0     
pytest-doctestplus                 0.2.0     
pytest-openfiles                   0.3.1     
pytest-remotedata                  0.3.1     
python-dateutil                    2.7.5     
pytz                               2018.7    
PyWavelets                         1.0.1     
PyYAML                             3.13      
pyzmq                              17.1.2    
QtAwesome                          0.5.3     
qtconsole                          4.4.3     
QtPy                               1.5.2     
requests                           2.21.0    
rope                               0.11.0    
ruamel-yaml                        0.15.46   
scikit-image                       0.14.1    
scikit-learn                       0.20.1    
scipy                              1.1.0     
seaborn                            0.9.0     
SecretStorage                      3.1.0     
Send2Trash                         1.5.0     
setuptools                         40.6.3    
simplegeneric                      0.8.1     
singledispatch                     3.4.0.3   
six                                1.12.0    
snowballstemmer                    1.2.1     
sortedcollections                  1.0.1     
sortedcontainers                   2.1.0     
Sphinx                             1.8.2     
sphinxcontrib-websupport           1.1.0     
spyder                             3.3.2     
spyder-kernels                     0.3.0     
SQLAlchemy                         1.2.15    
statsmodels                        0.9.0     
sympy                              1.3       
tables                             3.4.4     
tblib                              1.3.2     
terminado                          0.8.1     
testpath                           0.4.2     
toolz                              0.9.0     
tornado                            5.1.1     
tqdm                               4.28.1    
traitlets                          4.3.2     
unicodecsv                         0.14.1    
urllib3                            1.24.1    
wcwidth                            0.1.7     
webencodings                       0.5.1     
Werkzeug                           0.14.1    
wheel                              0.32.3    
widgetsnbextension                 3.4.2     
wrapt                              1.10.11   
wurlitzer                          1.0.2     
xlrd                               1.2.0     
XlsxWriter                         1.1.2     
xlwt                               1.3.0     
zict                               0.1.3    
```
Pip list.

**Comment by sobujmaroon** [comment]
```
# packages in environment at /home/ubuntu/anaconda3/envs/py39:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
addict                    2.4.0                     <pip>
ca-certificates           2021.7.5             h06a4308_1  
certifi                   2021.5.30        py39h06a4308_0  
charset-normalizer        2.0.6                     <pip>
click                     8.0.1                     <pip>
configparser              5.0.2                     <pip>
cycler                    0.10.0                    <pip>
Cython                    0.29.24                   <pip>
docker-pycreds            0.4.0                     <pip>
gitdb                     4.0.7                     <pip>
GitPython                 3.1.24                    <pip>
idna                      3.2                       <pip>
kiwisolver                1.3.2                     <pip>
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
matplotlib                3.4.3                     <pip>
mmcv-full                 1.3.14                    <pip>
mmdet                     2.17.0                    <pip>
ncurses                   6.2                  he6710b0_1  
numpy                     1.21.2                    <pip>
opencv-python             4.5.3.56                  <pip>
openssl                   1.1.1l               h7f8727e_0  
packaging                 21.0                      <pip>
pathtools                 0.1.2                     <pip>
Pillow                    8.3.2                     <pip>
pip                       21.2.4           py37h06a4308_0  
prettytable               2.2.1                     <pip>
promise                   2.3                       <pip>
protobuf                  3.18.0                    <pip>
psutil                    5.8.0                     <pip>
pycocotools               2.0.2                     <pip>
pyparsing                 2.4.7                     <pip>
python                    3.9.0                hdb3f193_2  
python-dateutil           2.8.2                     <pip>
PyYAML                    5.4.1                     <pip>
readline                  8.1                  h27cfd23_0  
requests                  2.26.0                    <pip>
sentry-sdk                1.4.3                     <pip>
setuptools                58.0.4           py39h06a4308_0  
shortuuid                 1.0.1                     <pip>
six                       1.16.0                    <pip>
smmap                     4.0.0                     <pip>
sqlite                    3.36.0               hc218d9a_0  
ssod                      0.0.1                     <pip>
subprocess32              3.5.4                     <pip>
termcolor                 1.1.0                     <pip>
terminaltables            3.1.0                     <pip>
tk                        8.6.11               h1ccaba5_0  
torch                     1.9.1                     <pip>
torchaudio                0.9.1                     <pip>
torchvision               0.10.1                    <pip>
typing-extensions         3.10.0.2                  <pip>
tzdata                    2021a                h5d7bf9c_0  
urllib3                   1.26.7                    <pip>
wandb                     0.12.2                    <pip>
wcwidth                   0.2.5                     <pip>
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                    <pip>
yaspin                    2.1.0                     <pip>
zlib                      1.2.11               h7b6447c_3  
(py39) ubuntu@ip-172-31-39-34:/data/SoftTeacher$ pip list
Package            Version   Location
------------------ --------- ----------------------------------------
addict             2.4.0
certifi            2021.5.30
charset-normalizer 2.0.6
click              8.0.1
configparser       5.0.2
cycler             0.10.0
Cython             0.29.24
docker-pycreds     0.4.0
gitdb              4.0.7
GitPython          3.1.24
idna               3.2
kiwisolver         1.3.2
matplotlib         3.4.3
mmcv-full          1.3.14
mmdet              2.17.0    /data/SoftTeacher/thirdparty/mmdetection
numpy              1.21.2
opencv-python      4.5.3.56
packaging          21.0
pathtools          0.1.2
Pillow             8.3.2
pip                21.2.4
prettytable        2.2.1
promise            2.3
protobuf           3.18.0
psutil             5.8.0
pycocotools        2.0.2
pyparsing          2.4.7
python-dateutil    2.8.2
PyYAML             5.4.1
requests           2.26.0
sentry-sdk         1.4.3
setuptools         58.0.4
shortuuid          1.0.1
six                1.16.0
smmap              4.0.0
ssod               0.0.1     /data/SoftTeacher
subprocess32       3.5.4
termcolor          1.1.0
terminaltables     3.1.0
torch              1.9.1
torchaudio         0.9.1
torchvision        0.10.1
typing-extensions  3.10.0.2
urllib3            1.26.7
wandb              0.12.2
wcwidth            0.2.5
wheel              0.37.0
yapf               0.31.0
yaspin             2.1.0
```

**Comment by MendelXu** [comment]
I see. I will try to build a similar environment to see whether there is any potential solution.

**Comment by MendelXu** [comment]
I have built a similar environment and it seems to work fine. (As my local machine can not support Cuda 11.2, I applied for a machine which is Cuda 11.4 but I think it should be fine for your case.)
- 1 Run this command:
  ```
   pip uninstall mmcv_full
   pip install mmcv-full --no-cache-dir
  ```
   If this does not work, try solution 2.
- 2 Download this file [link](https://drive.google.com/file/d/1ZxU4zWW0PK2ceQLlFoN20Nf2H2fbiDwZ/view?usp=sharing), install the package with 
```
conda env create -f env.yaml
conda activate debug
#assert you are in the root of this project
make install
pip uninstall mmcv_full
 pip install mmcv-full --no-cache-dir
```
